### PR TITLE
Fix copy-paste reference to SNMPv2 in README.md

### PR DESCRIPTION
**Pull request by initialed85**
While recommending this library to somebody I noticed the error in README.md

### CODE REVIEW

**Comment by DanielLeone** [comment]
I approve; good bananas 🍌  and carrots 🥕

**Comment by smills2929** [comment]
🥑

**Comment by smills2929** [comment]
Alright, I've spent hours reading over this PR (my reading speed isn't what it used to be), which shows my dedication, given that the PR has only been up for 15 mins. 

It looks good. I especially liked what you did with the place where you changed 'SNMPv2' to 'ODBC'. Actually, that was probably my favourite part, if I'm to be honest.

Approved.

**Comment by initialed85** [comment]
> Alright, I've spent hours reading over this PR (my reading speed isn't what it used to be), which shows my dedication, given that the PR has only been up for 15 mins.
> 
> It looks good. I especially liked what you did with the place where you changed 'SNMPv2' to 'ODBC'. Actually, that was probably my favourite part, if I'm to be honest.
> 
> Approved.

Thank you for your service.

**Review by smills2929 — APPROVED** [review]
Great usage of letters.

**Pull request merged**
